apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-authentication-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: any-ms-authentication
  template:
    metadata:
      labels:
        app: any-ms-authentication
    spec:
      containers:
        - name: any-ms-authentication
          image: goany/any-ms-authentication
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://ms-nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "goany"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-password
                  key: MONGO_PASSWORD
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-username
                  key: MONGO_USERNAME
