apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: any-ms-nats
  template:
    metadata:
      labels:
        app: any-ms-nats
    spec:
      containers:
        - name: any-ms-nats
          image: nats-streaming:0.17.0
          args:
            [
              "-p",
              "4222",
              "-m",
              "8222",
              "-hbi",
              "5s",
              "-hbt",
              "5s",
              "-hbf",
              "2",
              "-SD",
              "-cid",
              "goany",
            ]
